version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
        - CONFIG_USER_NAME=${CONFIG_USER_NAME}
        - CONFIG_PASSWORD=${CONFIG_PASSWORD}
    ports:
      - "8019:8018"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - ENVIRONMENT=local
      - AUTH_ENABLED=false
    networks:
      - defnet

networks:
  defnet:
    external: true