server.port : 8019

#localhost setup
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/iliad?currentSchema=andro
    username: developer
    password: testing
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto : create